[package]
name = "schemars-interactive"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = "0.8.8"
serde_json = "1"
serde = { version = "1", default-features = false, features = ["derive"] }
thiserror = "1.0.31"
inquire = "0.5.2"